### PR TITLE
Feature/dequeue assets

### PR DESCRIPTION
**Pull request by IvanGrginovInf**
Added a class that enables dequeueing any plugin's assets for all pages where they aren't used (developer needs to define this logic on a per-plugin basis)

Usage is as follows:
---
1. Create a new function that wraps $this->dequeue_plugin_on
2. 1st param === plugin's slug
3. 2nd param === a custom check (anon function, returns bool) which determines where to keep / where to dequeue assets
4. Hook the new function to 'wp_print_scripts' and 'wp_print_styles' actions with high priority (>100)

Tested with contact-form-7.

### CODE REVIEW

**Comment by IvanGrginovInf** [comment]
@iruzevic Yup, I agree that there shouldn't be any references to other plugins, the cf7 function is only there as an example, it doesn't actually do anything.

**Comment by iruzevic** [comment]
@IvanGrginovInf everything that is not used should not be there. If you have an example put it inside the Wiki.

**Comment by dingo-d** [comment]
Like the idea, but it should be merged to the feature branch that we will use in our project. 
For now, it would be better to add this in wiki with concrete use example so that people can use it if they want to.

The more documentation and examples we have, the bigger the reach will be :) 

I'll close this for now. @IvanGrginovInf when you find the time, please add this to wiki as a separate page.

**Comment by IvanGrginovInf** [comment]
Np, will do. 👍

**Pull request closed without merging**
