### PR TITLE
Tweaking setup script for 4.0.0

### PR DESCRIPTION
**Pull request by IvanGrginovInf**

### CODE REVIEW

**Comment by dingo-d** [comment]
The travis will fail until the eightshift libs are updated. You used the recommended php version to 7.0

> Problem 1
    - Installation request for infinum/eightshift-libs dev-master -> satisfiable by infinum/eightshift-libs[dev-master].
    - infinum/eightshift-libs dev-master requires php >=7.2 -> your PHP version (7.0.25) does not satisfy that requirement.

We should also make a version check inside the code as well.

**Comment by IvanGrginovInf** [comment]
@dingo-d The error is because Travis is set to check versions 7.1 and 7.0, both of which we can't support with libs (`min php version: >= 7.2`). We can just remove those 2 versions from Travis.

**Comment by dingo-d** [comment]
Or we change the requirement in the libs? We should always check the code against the latest PHP version.

**Comment by IvanGrginovInf** [comment]
@dingo-d not sure what you mean, we already have it set: https://github.com/infinum/eightshift-libs/blob/develop/composer.json

```json
  "require": {
    "php": ">=7.2",
    "php-di/php-di": "^6.0"
  },
```

How does Travis decide which versions to test? You specify them or it looks at `composer.json`?

**Comment by dingo-d** [comment]
What I meant was to set the `"php": ">=7.0"` in the libs composer. 

What travis does is use the `matrix` part and performs installation for every version that is mentioned in the file.

If you take a look here: https://travis-ci.org/infinum/wp-boilerplate/builds/549093919?utm_source=github_status&utm_medium=notification
You can notice that there are 9 separate jobs - based on the travis setup. So on every version it tries to install what is set in the `before_install` step on every virtual server.

**Comment by IvanGrginovInf** [comment]
> The only thing that is slightly worrying is the `--ignore-platform-reqs`option in composer install, but I guess this is ok to ignore?

Without this the script will check the user's local php version (which is irrelevant regardless, but especially if user is planning to develop site in a container - such as VVV or Local). This would only make sense if the user is using something like XAMP / MAMP.

I don't see a way around it unless we want to complicate the setup script with setting up the user's development environment as well.

**Pull request merged**
